# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  # - name: Hugging Face
  #   url: 'https://huggingface.co/indefeasible'
  #   weight: 20
  - name: Reading List
    url: https://cpwburkajrjwgfdbvjzt.supabase.co/storage/v1/object/sign/pdf-43a55472-27bd-43ad-ab0d-674d586bf45a/Academic%20Reading%20List?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJwZGYtNDNhNTU0NzItMjdiZC00M2FkLWFiMGQtNjc0ZDU4NmJmNDVhL0FjYWRlbWljIFJlYWRpbmcgTGlzdCIsImlhdCI6MTcxNDc1OTMxNiwiZXhwIjoxNzE0ODQ1NzE2fQ.hbgcE1RK4ISUopg-E-B8J5BvUQuoZ45HYNMea7An8DU
    weight: 20
  # - name: Talks
  #   url: '#talks'
  #   weight: 40
  # - name: Publications
  #   url: '#featured'
  #   weight: 50
  - name: Mailing List
    url: '#contact'
    weight: 30 # -> 60 

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: Reading List
#    url: uploads/reading_list.pdf
#    weight: 40
